const Battle = require("./battle/Battle");

const team = [
  {
    name: 'Venusaur',
    species: 'venusaur',
    gender: 'M',
    moves: ['sleeppowder', 'sludgebomb', 'leafstorm', 'protect'],
    ability: 'chlorophyll',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'widelens',
    level: 50,
    shiny: false,
    nature: 'timid',
  },
  {
    name: 'Torkoal',
    species: 'torkoal',
    gender: 'M',
    moves: ['eruption', 'heatwave', 'solarbeam', 'earthpower'],
    ability: 'drought',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'charcoal',
    level: 50,
    shiny: false,
    nature: 'quiet',
  },
  {
    name: 'Conkeldurr',
    species: 'conkeldurr',
    gender: 'M',
    moves: ['machpunch', 'drainpunch', 'icepunch', 'protect'],
    ability: 'ironfist',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'lifeorb',
    level: 50,
    shiny: false,
    nature: 'adamant',
  },
  {
    name: 'Hatterene',
    species: 'hatterene',
    gender: 'F',
    moves: ['dazzlinggleam', 'psychic', 'trickroom', 'protect'],
    ability: 'magicbounce',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'focussash',
    level: 50,
    shiny: false,
    nature: 'quiet',
  },
  {
    name: 'Incineroar',
    species: 'incineroar',
    gender: 'M',
    moves: ['fakeout', 'flareblitz', 'partingshot', 'darkestlariat'],
    ability: 'intimidate',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'assaultvest',
    level: 50,
    shiny: false,
    nature: 'careful',
  },
  {
    name: 'Dusclops',
    species: 'dusclops',
    gender: 'M',
    moves: ['trickroom', 'nightshade', 'painsplit', 'willowisp'],
    ability: 'frisk',
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    item: 'eviolite',
    level: 50,
    shiny: false,
    nature: 'relaxed',
  },
];

const battle = new Battle();
battle.setPlayer();
battle.setPlayer();
battle.start();
